import type { BlockPreset } from '../types'

export const ctaPresets: BlockPreset[] = [
  {
    id: 'default-cta',
    name: 'Default CTA',
    description: 'Centered CTA with white card on indigo background',
    data: {
      variant: 'default',
      layout: 'centered',
      sectionLabel: 'Get started today',
      heading: 'Ready to build something great?',
      subheading: 'Join thousands of teams already using our platform. Free to start, no credit card required.',
      primaryCtaLabel: 'Start for free',
      primaryCtaUrl: '/signup',
      secondaryCtaLabel: 'Talk to sales',
      secondaryCtaUrl: '/contact',
    },
  },
  {
    id: 'gradient-cta',
    name: 'Gradient CTA',
    description: 'Bold gradient CTA for high-conversion sections',
    data: {
      variant: 'gradient',
      layout: 'centered',
      heading: 'Start building for free',
      subheading: 'No setup fees. No contracts. Cancel anytime.',
      primaryCtaLabel: 'Create your account',
      primaryCtaUrl: '/signup',
      secondaryCtaLabel: 'See pricing',
      secondaryCtaUrl: '/pricing',
    },
  },
  {
    id: 'dark-cta',
    name: 'Dark CTA',
    description: 'Dark card CTA for dark-themed pages',
    data: {
      variant: 'dark',
      layout: 'centered',
      sectionLabel: 'Limited time offer',
      heading: 'Get 3 months free on any plan',
      subheading: 'Use code LAUNCH at checkout. Offer ends soon.',
      primaryCtaLabel: 'Claim offer',
      primaryCtaUrl: '/pricing',
      secondaryCtaLabel: 'Learn more',
      secondaryCtaUrl: '/offer',
    },
  },
  {
    id: 'split-cta',
    name: 'Split CTA',
    description: 'Text left, buttons right layout',
    data: {
      variant: 'minimal',
      layout: 'split',
      heading: 'Transform your content workflow',
      subheading: 'Give your team the tools they need to move faster.',
      primaryCtaLabel: 'Get started',
      primaryCtaUrl: '/signup',
      secondaryCtaLabel: 'Schedule a demo',
      secondaryCtaUrl: '/demo',
    },
  },
  {
    id: 'brand-cta',
    name: 'Brand CTA',
    description: 'Solid indigo brand section',
    data: {
      variant: 'brand',
      layout: 'centered',
      heading: 'The CMS your team deserves',
      subheading: 'Powerful enough for developers. Intuitive enough for everyone else.',
      primaryCtaLabel: 'Try it free',
      primaryCtaUrl: '/signup',
      secondaryCtaLabel: 'Read case studies',
      secondaryCtaUrl: '/customers',
    },
  },
]
