import type { BlockPreset } from '../types'

export const pricingPresets: BlockPreset[] = [
  {
    id: 'saas-pricing',
    name: 'SaaS Pricing',
    description: '3-tier pricing with highlighted middle plan',
    data: {
      variant: 'default',
      sectionLabel: 'Pricing',
      heading: 'Simple, transparent pricing',
      subheading: 'No hidden fees. No surprises. Start free and scale as you grow.',
      plans: [
        {
          name: 'Starter',
          description: 'Perfect for indie developers and small projects.',
          price: '$0',
          period: '/month',
          badge: 'Free forever',
          features: [
            { text: 'Up to 3 projects' },
            { text: '2 team members' },
            { text: '5GB storage' },
            { text: 'Community support' },
            { text: 'Basic analytics' },
          ],
          ctaLabel: 'Get started free',
          ctaUrl: '/signup',
        },
        {
          name: 'Pro',
          description: 'For growing teams that need more power and flexibility.',
          price: '$49',
          period: '/month',
          highlighted: true,
          badge: 'Most popular',
          features: [
            { text: 'Unlimited projects' },
            { text: 'Up to 10 team members' },
            { text: '50GB storage' },
            { text: 'Priority support (24h)' },
            { text: 'Advanced analytics' },
            { text: 'Custom domains' },
            { text: 'Live Preview' },
          ],
          ctaLabel: 'Start Pro trial',
          ctaUrl: '/signup?plan=pro',
        },
        {
          name: 'Enterprise',
          description: 'For large organizations with advanced security and compliance needs.',
          price: '$199',
          period: '/month',
          features: [
            { text: 'Unlimited everything' },
            { text: 'Unlimited team members' },
            { text: '500GB storage' },
            { text: 'Dedicated support (1h SLA)' },
            { text: 'SSO & SAML' },
            { text: 'Audit logs' },
            { text: 'Custom SLA' },
            { text: 'On-premise option' },
          ],
          ctaLabel: 'Talk to sales',
          ctaUrl: '/contact',
        },
      ],
    },
  },
  {
    id: 'gradient-pricing',
    name: 'Gradient Pricing',
    description: '3-tier gradient pricing with highlighted plan',
    data: {
      variant: 'gradient',
      sectionLabel: 'Plans',
      heading: 'Invest in your content',
      subheading: 'Every plan includes a 14-day free trial. No credit card required.',
      plans: [
        {
          name: 'Hobby',
          description: 'For side projects and personal portfolios.',
          price: 'Free',
          features: [
            { text: '1 project' },
            { text: 'Community support' },
            { text: '1GB storage' },
          ],
          ctaLabel: 'Get started',
          ctaUrl: '/signup',
        },
        {
          name: 'Team',
          description: 'For product teams shipping at speed.',
          price: '$79',
          period: '/month',
          highlighted: true,
          badge: 'Best value',
          features: [
            { text: 'Unlimited projects' },
            { text: '15 team members' },
            { text: '100GB storage' },
            { text: 'Live Preview' },
            { text: 'Priority support' },
          ],
          ctaLabel: 'Start free trial',
          ctaUrl: '/signup?plan=team',
        },
        {
          name: 'Scale',
          description: 'For organizations with custom requirements.',
          price: 'Custom',
          features: [
            { text: 'Everything in Team' },
            { text: 'Custom contract' },
            { text: 'Dedicated infra' },
            { text: 'SLA guarantee' },
          ],
          ctaLabel: 'Contact us',
          ctaUrl: '/contact',
        },
      ],
    },
  },
  {
    id: 'dark-pricing',
    name: 'Dark Pricing',
    description: 'Dark theme 3-tier pricing',
    data: {
      variant: 'dark',
      sectionLabel: 'Pricing',
      heading: 'Pay for what you use',
      subheading: 'Predictable pricing with no surprise bills.',
      plans: [
        {
          name: 'Basic',
          description: 'For individuals and small teams.',
          price: '$19',
          period: '/month',
          features: [
            { text: '5 projects' },
            { text: '3 seats' },
            { text: '10GB storage' },
          ],
          ctaLabel: 'Get started',
          ctaUrl: '/signup',
        },
        {
          name: 'Growth',
          description: 'For scaling teams that need more.',
          price: '$99',
          period: '/month',
          highlighted: true,
          badge: 'Recommended',
          features: [
            { text: 'Unlimited projects' },
            { text: '20 seats' },
            { text: '200GB storage' },
            { text: 'Advanced features' },
          ],
          ctaLabel: 'Start trial',
          ctaUrl: '/signup?plan=growth',
        },
        {
          name: 'Enterprise',
          description: 'Custom solutions for large teams.',
          price: 'Custom',
          features: [
            { text: 'Everything in Growth' },
            { text: 'Unlimited seats' },
            { text: 'Custom storage' },
            { text: 'Dedicated SLA' },
          ],
          ctaLabel: 'Contact sales',
          ctaUrl: '/contact',
        },
      ],
    },
  },
]
