import type { BlockPreset } from '../types'

export const heroBannerPresets: BlockPreset[] = [
  {
    id: 'saas-hero',
    name: 'SaaS Hero',
    description: 'Two-column hero with dashboard mockup and social proof',
    data: {
      variant: 'default',
      spacing: 'normal',
      badge: 'New — Version 3.0 released',
      heading: 'Build faster with',
      headingHighlight: 'dynamic blocks',
      description: 'Compose beautiful pages from reusable content blocks. No code needed — just drag, drop, and publish.',
      primaryCtaLabel: 'Get started free',
      primaryCtaUrl: '/get-started',
      secondaryCtaLabel: 'Watch demo',
      secondaryCtaUrl: '/demo',
      socialProofText: 'Trusted by 9,000+ teams worldwide',
    },
  },
  {
    id: 'dark-hero',
    name: 'Dark Hero',
    description: 'Dark background hero for modern SaaS products',
    data: {
      variant: 'dark',
      spacing: 'normal',
      badge: 'Now in public beta',
      heading: 'Ship your product',
      headingHighlight: '10x faster',
      description: 'The all-in-one platform for teams that move fast. Built for scale, designed for speed.',
      primaryCtaLabel: 'Start building',
      primaryCtaUrl: '/signup',
      secondaryCtaLabel: 'View docs',
      secondaryCtaUrl: '/docs',
      socialProofText: 'Join 5,000+ developers building with us',
    },
  },
  {
    id: 'gradient-hero',
    name: 'Gradient Hero',
    description: 'Bold gradient background for agency or launch pages',
    data: {
      variant: 'gradient',
      spacing: 'spacious',
      badge: '🚀 Just launched',
      heading: 'Your vision,',
      headingHighlight: 'beautifully built',
      description: 'We design and build digital experiences that convert visitors into customers.',
      primaryCtaLabel: 'Start your project',
      primaryCtaUrl: '/contact',
      secondaryCtaLabel: 'See our work',
      secondaryCtaUrl: '/portfolio',
    },
  },
  {
    id: 'centered-hero',
    name: 'Centered Hero',
    description: 'Centered layout for product launches and landing pages',
    data: {
      variant: 'centered',
      spacing: 'spacious',
      badge: 'Introducing v2.0',
      heading: 'The future of',
      headingHighlight: 'content management',
      description: 'A smarter way to build, manage, and publish content. Flexible enough for any team, powerful enough for any scale.',
      primaryCtaLabel: 'Get early access',
      primaryCtaUrl: '/early-access',
      secondaryCtaLabel: 'Learn more',
      secondaryCtaUrl: '/about',
      socialProofText: '2,000+ people on the waitlist',
    },
  },
  {
    id: 'minimal-hero',
    name: 'Minimal Hero',
    description: 'Clean minimal hero for product or documentation sites',
    data: {
      variant: 'minimal',
      spacing: 'normal',
      heading: 'Simple, powerful,',
      headingHighlight: 'extensible',
      description: 'Everything you need to build great products. Nothing you don\'t.',
      primaryCtaLabel: 'Read the docs',
      primaryCtaUrl: '/docs',
      secondaryCtaLabel: 'View on GitHub',
      secondaryCtaUrl: 'https://github.com',
    },
  },
]
